apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jgr-task-0.2
  namespace: default
spec:
  description: |-
    This task runs commands against the cluster provided by user and if not provided then where the Task is being executed.
    `ibm-pak` provides the IBM Catalog Management plug-in for IBM Cloud Paks. The plugin streamlines the deployment of IBM Cloud Paks in a disconnected environment, which was done earlier using cloudctl.
    This task uses the quay.io/ibmtz/ibm-pak-ubi:v1.14.0 image. This comes with oc, ibm-pak, jq, yq, git, unzip and zip
  params:
  - default: oc ibm-pak help
    description: The OpenShift CLI arguments to run
    name: SCRIPT
    type: string
  results:
  - description: The output of the task
    name: output
    type: string
  steps:
  - computeResources: {}
    env:
    - name: HOME
      value: /tekton/home
    image: quay.io/jgomezr/jgr-pak-ubi:v1.15.0
    name: oc
    script: |
      #!/usr/bin/env bash

      [[ "$(workspaces.manifest-dir.bound)" == "true" ]] && \
      cd $(workspaces.manifest-dir.path)

      [[ "$(workspaces.kubeconfig-dir.bound)" == "true" ]] && \
      [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]] && \
      export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig

      $(params.SCRIPT)
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
  workspaces:
  - description: The workspace which contains resources for CP4I deployment.
    name: cp4i-ws
    optional: true
  - description: The workspace which contains kubernetes manifests which we want to
      apply on the cluster.
    name: manifest-dir
    optional: true
  - description: The workspace which contains the the kubeconfig file if in case we
      want to run the oc command on another cluster.
    name: kubeconfig-dir
    optional: true
